# 服务器配置
server:
  port: 9999
  servlet:
    context-path: /

spring:
  # 默认是懒加载,取消懒加载
  mvc:
    servlet:
      load-on-startup: 1

  # 热部署配置
  devtools:
    restart:
      # 热部署生效
      enabled: true
      # 设置重启的目录
      additional-paths: src/main/java

  # 数据源配置
  datasource:
    # 配置数据库
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/fighting?characterEncoding=utf-8&useSSL=false
    #配置连接池
    hikari:
      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      connection-timeout: 30000
      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      idle-timeout: 180000
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒
      max-lifetime: 1800000
      # 连接池中允许的最大连接数。缺省值：10
      maximum-pool-size: 50
      minimum-idle: 5
      connection-test-query: SELECT 1

  # spring cache配置
  cache:
    redis:
      time-to-live: 900s

  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 15
    host: localhost
    port: 6379
    password: redis
    # 连接超时时间(毫秒)
    timeout: 3000
    # 连接池配置
    jedis:
      pool:
        # 连接池最大连接数
        max-active: 50
        # 连接池最大阻塞等待时间
        max-wait: -1
        # 连接池最大空闲连接
        max-idle: 5
        # 连接池最小空闲连接
        min-idle: 1

# 自定义配置
custom:
  result:
    suffix: ~.~
  jwt:
    # token 过期时间（秒）
    expirationSecond: 900
    # token 刷新时间（天）
    validTime: 7
    # 以旧换新有效时长（秒）
    oldChangeNewSecond: 30
  upload:
    # 上传文件的路径
    path: /fightingUploadPath/
    # 静态资源对外暴露的访问路径
    staticAccessPath: /fileServer/**
  # 个人模式
  individualModel: false