# 使用哪个配置
spring:
  profiles:
    active: @package.environment@
  servlet:
    multipart:
      # 单个文件的最大值
      max-file-size: 5MB
      # 上传文件总的最大值
      max-request-size: 10MB

# mybatis配置
mybatis:
  # 配置实体类路径
  type-aliases-package: com.kon.fighting.entity
  # mapper.xml文件路径
  mapper-locations: classpath:mapper/*.xml
  # 下划线转驼峰
  configuration:
    map-underscore-to-camel-case: true

# 分页插件配置
pagehelper:
  # 指定数据库
  helper-dialect: mysql
  # 当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询
  reasonable: false
  # 用于从对象中根据属性名取值,可以配置pageNum,pageSize,count,pageSizeZero,reasonable。不配置映射的用默认值
  params: count=countsql
  # 分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  support-methods-arguments: true